kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true # disable kindnet
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: ./plugins/bin 
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: ./plugins/bin 
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: ./plugins/bin 
      containerPath: /opt/cni/bin
